[phases.setup]
nixPkgs = ["python312", "cairo", "pango", "gdk-pixbuf", "gobject-introspection", "harfbuzz", "fontconfig", "freetype", "libffi", "chromium"]

[phases.install]
cmds = ["pip install -r requirements.txt", "playwright install chromium --with-deps"]
